require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const fs = require('fs');
const path = require('path');
const https = require('https');

const PENDING_DIR = path.join(__dirname, '..', 'vault', 'System_Evolution', 'Pending');
const PROPOSAL_DIR = path.join(__dirname, '..', 'vault', 'System_Evolution', 'Proposals');

const GROQ_API_KEY = process.env.GROQ_API_KEY;

if (!fs.existsSync(PROPOSAL_DIR)) fs.mkdirSync(PROPOSAL_DIR, { recursive: true });

function callGroqStrategist(promptText) {
    return new Promise((resolve, reject) => {
        if (!GROQ_API_KEY) return reject(new Error('GROQ_API_KEY is not defined in .env'));

        const payload = JSON.stringify({
            model: 'qwen/qwen3.8-27b',
            max_tokens: 800,
            messages: [
                {
                    role: 'system',
                    content: `You are Monty, Chief Strategist and Advisor for Warlord Inc.
Your role: Review architectural candidates approved by Tess and formulate a concrete, atomic Change Manifest.

MCNC Operational Realities:
- Base Directory: C:\\Warlord_Inc\\Warlord_WASP\\MCNC
- Core Server: server.js (Express, Node.js, WebSockets on port 3001)
- Cockpit UI: src/tabs/Tab*.jsx (React / Vite)
- Indicator Rules: DodgerBlue, OrangeRed, Goldenrod LINES ONLY. No histograms. Zero-state init.

OUTPUT FORMAT:
Respond ONLY with a valid JSON object:
{
  "proposalId": "PROP-<auto-generated-short-id>",
  "title": "<Concise 1-line title>",
  "executiveSummary": "<2-sentence summary for Mike>",
  "riskLevel": "LOW" | "MEDIUM" | "HIGH",
  "targetFiles": ["<relative path from MCNC root>"],
  "actionPlan": [
    "<Step 1>",
    "<Step 2>",
    "<Step 3>"
  ],
  "verificationCommand": "<e.g. node -c server.js>"
}`
                },
                {
                    role: 'user',
                    content: promptText
                }
            ],
            temperature: 0.1,
            response_format: { type: "json_object" }
        });

        const req = https.request('https://api.groq.com/openai/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${GROQ_API_KEY}`,
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(payload)
            }
        }, (res) => {
            let body = '';
            res.on('data', chunk => body += chunk);
            res.on('end', () => {
                try {
                    const parsed = JSON.parse(body);
                    if (parsed.choices && parsed.choices[0]) {
                        resolve(JSON.parse(parsed.choices[0].message.content.trim()));
                    } else {
                        reject(new Error(body));
                    }
                } catch (e) {
                    reject(e);
                }
            });
        });

        req.on('error', reject);
        req.write(payload);
        req.end();
    });
}

async function processPendingCandidates() {
    if (!fs.existsSync(PENDING_DIR)) {
        console.log('[MONTY] No pending candidates found.');
        return;
    }

    const files = fs.readdirSync(PENDING_DIR).filter(f => f.endsWith('.json'));
    if (files.length === 0) {
        console.log('[MONTY] Pending queue is empty.');
        return;
    }

    console.log(`[MONTY STRATEGIST] Found ${files.length} candidate(s) awaiting strategic formulation...`);

    for (const file of files) {
        const candidatePath = path.join(PENDING_DIR, file);
        const candidateData = JSON.parse(fs.readFileSync(candidatePath, 'utf8'));

        console.log(`[MONTY] Analyzing candidate: ${candidateData.sourceDossier}...`);

        try {
            const proposal = await callGroqStrategist(JSON.stringify(candidateData, null, 2));
            proposal.sourceCandidate = file;
            proposal.generatedAt = new Date().toISOString();

            const outPath = path.join(PROPOSAL_DIR, `proposal_${file}`);
            fs.writeFileSync(outPath, JSON.stringify(proposal, null, 2), 'utf8');

            console.log(`  └─> [PROPOSAL GENERATED] Ready for Mike's Cockpit Approval: ${path.basename(outPath)}`);
            await new Promise(r => setTimeout(r, 3000));
        } catch (err) {
            console.error(`[MONTY ERROR] Failed on ${file}:`, err.message);
        }
    }

    console.log('[MONTY STRATEGY COMPLETE] Proposals ready for Cockpit Execution Gate.');
}

if (require.main === module) {
    processPendingCandidates();
}

module.exports = { processPendingCandidates };
